- name: Kubernetes met Azure Arc
  href: index.yml
- name: Overzicht
  items:
    - name: Over Kubernetes met Azure Arc
      href: overview.md
    - name: Azure Arc-validatie programma
      href: validation-program.md
- name: Snelstartgidsen
  items:
    - name: Een cluster verbinden met Azure Arc
      href: quickstart-connect-cluster.md
- name: Zelfstudies
  items:
    - name: Configuraties implementeren met GitOps
      href: tutorial-use-gitops-connected-cluster.md
    - name: CI/CD implementeren met GitOps
      href: tutorial-gitops-ci-cd.md
- name: Concepten
  items:
    - name: Agent architectuur
      href: conceptual-agent-architecture.md
    - name: Configuraties en GitOps
      href: conceptual-configurations.md
    - name: CI/CD-werk stroom met behulp van GitOps
      href: conceptual-gitops-ci-cd.md
    - name: Veelgestelde vragen
      href: faq.md
- name: Instructiegidsen
  items:
    - name: Verbinding maken met Azure Arc
      items:
        - name: Onboarding van een service-principal
          href: create-onboarding-service-principal.md
    - name: Beheren
      items:
        - name: Agent-upgrades
          href: agent-upgrade.md
    - name: Scenario's
      items:
        - name: Helm-grafieken implementeren met GitOps
          href: use-gitops-with-helm.md
        - name: GitOps afdwingen met Azure Policy
          href: use-azure-policy.md
        - name: Bewaken met Azure Monitor voor containers
          href: ../../azure-monitor/containers/container-insights-enable-arc-enabled-clusters.md?toc=%2fazure%2fazure-arc%2fkubernetes%2ftoc.yml
        - name: Toegangsbeheer beleid met Azure Policy
          href: ../../governance/policy/concepts/policy-for-kubernetes.md?toc=/azure/azure-arc/kubernetes/toc.yml
        - name: IoT-workloads implementeren
          href: deploy-azure-iot-edge-workloads.md
    - name: Problemen oplossen
      href: Troubleshooting.md
- name: Naslaginformatie
  items:
    - name: Ingebouwde modules voor Azure Policy
      displayName: 'samples, policies, definitions'
      href: policy-reference.md
    - name: Azure PowerShell
      href: /powershell/module/Az.ConnectedKubernetes/
- name: Resources
  items:
    - name: Azure Arc-snelstart
      href: 'https://azurearcjumpstart.io'